import { RoadMapResponse, Roadmap } from './types';

const careerRoadmap: Roadmap[] = [
  {
    id: '1',
    name: 'Junior Software Engineer',
    links: [],
    description: 'Entry-level position for software development.',
    emoji: '👨‍💻',
    parentIds: [],
  },
  {
    id: '2',
    name: 'Software Engineer',
    links: [],
    description: 'Mid-level position for software development.',
    emoji: '💾',
    parentIds: ['1'],
  },
  {
    id: '3',
    name: 'Senior Software Engineer',
    links: [],
    description: 'Advanced level position for software development.',
    emoji: '🚀',
    parentIds: ['2'],
  },
  {
    id: '4',
    name: 'Team Leader',
    links: [],
    description: 'Responsible for leading a software development team.',
    emoji: '👨‍🔧',
    parentIds: ['3'],
  },
  {
    id: '41',
    name: 'Engineering Manager',
    links: [],
    description: 'Responsible for leading a software development team.',
    emoji: '📊',
    parentIds: ['4'],
  },
  {
    id: '42',
    name: 'Senior Engineering Manager',
    links: [],
    description: 'Responsible for leading a software development team.',
    emoji: '👨‍💼',
    parentIds: ['41'],
  },
  {
    id: '43',
    name: 'Director of Engineering',
    links: [],
    description: 'Responsible for leading a software development team.',
    emoji: '🏢',
    parentIds: ['42'],
  },
  {
    id: '5',
    name: 'Technical Leader',
    links: [],
    description: 'Responsible for technical decisions and architecture.',
    emoji: '⚙️',
    parentIds: ['3'],
  },
  {
    id: '51',
    name: 'Principal Architect',
    links: [
      'https://example.com/difference-architect-principal',
      'https://example.com/principal-architect-roles',
    ],
    longDescription:
      'A Principal Architect, often considered a senior-level technical role, is responsible for the technical direction and design choices in projects, ensuring that the architecture aligns with business objectives. They collaborate closely with stakeholders, other architects, and teams to deliver scalable, robust, and high-performing solutions. Their expertise often spans across multiple domains and technologies, enabling them to guide projects to successful outcomes. Beyond technical prowess, they are also expected to mentor junior architects and play an instrumental role in strategic planning.',
    description: 'Responsible for technical decisions and architecture.',
    emoji: '📐',
    parentIds: ['5'],
  },
  {
    id: '52',
    name: 'Senior Principal Architect',
    links: [],
    description: 'Responsible for technical decisions and architecture.',
    emoji: '📏',
    parentIds: ['51'],
  },
  {
    id: '53',
    name: 'Staff Engineer',
    links: [],
    description: 'Responsible for technical decisions and architecture.',
    emoji: '🔍',
    parentIds: ['52'],
  },
  {
    id: '6',
    name: 'Senior Architect',
    links: [],
    description: 'Focuses on high-level design and architecture.',
    emoji: '🏛️',
    parentIds: ['3'],
  },
  {
    id: '61',
    name: 'Senior solution Architect',
    links: [],
    description: 'Focuses on high-level design and architecture.',
    emoji: '🌐',
    parentIds: ['6'],
  },
  {
    id: '62',
    name: 'Chief Architect',
    links: [],
    description: 'Focuses on high-level design and architecture.',
    emoji: '🌍',
    parentIds: ['61'],
  },
  {
    id: '7321',
    name: 'VP of Engineering',
    links: [],
    description: 'Focuses on high-level design and architecture.',
    emoji: '👑',
    parentIds: ['62', '53', '43'],
  },
];

export const responseData: RoadMapResponse[] = [
  {
    roadMapName: 'developer',
    roadMap: careerRoadmap,
  },
];
